# Questo file contiene la mappatura completa di tutte le 235 etichette
# estratte dal file labels.csv

LABEL_TO_NAME = {
    'ace': 'Achinese', # 
    'afr': 'Afrikaans', # 
    'als': 'Alemannic German', # 
    'amh': 'Amharic', # 
    'ang': 'Old English', # 
    'ara': 'Arabic', # 
    'arg': 'Aragonese', # 
    'arz': 'Egyptian Arabic', # 
    'asm': 'Assamese', # 
    'ast': 'Asturian', # 
    'ava': 'Avar', # [cite: 2]
    'aym': 'Aymara', # [cite: 2]
    'azb': 'South Azerbaijani', # [cite: 2]
    'aze': 'Azerbaijani', # [cite: 2]
    'bak': 'Bashkir', # [cite: 2]
    'bar': 'Bavarian', # [cite: 2]
    'bcl': 'Central Bikol', # [cite: 2]
    'be-tarask': 'Belarusian (Taraschkewiza)', # [cite: 2]
    'bel': 'Belarusian', # [cite: 2]
    'ben': 'Bengali', # [cite: 2]
    'bho': 'Bhojpuri', # [cite: 2]
    'bjn': 'Banjar', # [cite: 2]
    'bod': 'Tibetan', # [cite: 2]
    'bos': 'Bosnian', # [cite: 2]
    'bpy': 'Bishnupriya', # [cite: 3]
    'bre': 'Breton', # [cite: 3]
    'bul': 'Bulgarian', # [cite: 3]
    'bxr': 'Buryat', # [cite: 3]
    'cat': 'Catalan', # [cite: 3]
    'cbk': 'Chavacano', # [cite: 3]
    'cdo': 'Min Dong', # [cite: 3]
    'ceb': 'Cebuano', # [cite: 3]
    'ces': 'Czech', # [cite: 3]
    'che': 'Chechen', # [cite: 3]
    'chr': 'Cherokee', # [cite: 3]
    'chv': 'Chuvash', # [cite: 3]
    'ckb': 'Central Kurdish', # [cite: 3]
    'cor': 'Cornish', # [cite: 3]
    'cos': 'Corsican', # [cite: 4]
    'crh': 'Crimean Tatar', # [cite: 4]
    'csb': 'Kashubian', # [cite: 4]
    'cym': 'Welsh', # [cite: 4]
    'dan': 'Danish', # [cite: 4]
    'deu': 'German', # [cite: 4]
    'diq': 'Dimli', # [cite: 4]
    'div': 'Dhivehi', # [cite: 4]
    'dsb': 'Lower Sorbian', # [cite: 4]
    'dty': 'Doteli', # [cite: 4]
    'egl': 'Emilian', # [cite: 4]
    'ell': 'Modern Greek', # [cite: 4]
    'eng': 'English', # [cite: 4]
    'epo': 'Esperanto', # [cite: 4]
    'est': 'Estonian', # [cite: 4]
    'eus': 'Basque', # [cite: 4]
    'ext': 'Extremaduran', # [cite: 5]
    'fao': 'Faroese', # [cite: 5]
    'fas': 'Persian', # [cite: 5]
    'fin': 'Finnish', # [cite: 5]
    'fra': 'French', # [cite: 5]
    'frp': 'Arpitan', # [cite: 5]
    'fry': 'Western Frisian', # [cite: 5]
    'fur': 'Friulian', # [cite: 5]
    'gag': 'Gagauz', # [cite: 5]
    'gla': 'Scottish Gaelic', # [cite: 5]
    'gle': 'Irish', # [cite: 5]
    'glg': 'Galician', # [cite: 5]
    'glk': 'Gilaki', # [cite: 5]
    'glv': 'Manx', # [cite: 5]
    'grn': 'Guarani', # [cite: 5]
    'guj': 'Gujarati', # [cite: 5]
    'hak': 'Hakka Chinese', # [cite: 5]
    'hat': 'Haitian Creole', # [cite: 6]
    'hau': 'Hausa', # [cite: 6]
    'hbs': 'Serbo-Croatian', # [cite: 6]
    'heb': 'Hebrew', # [cite: 6]
    'hif': 'Fiji Hindi', # [cite: 6]
    'hin': 'Hindi', # [cite: 6]
    'hrv': 'Croatian', # [cite: 6]
    'hsb': 'Upper Sorbian', # [cite: 6]
    'hun': 'Hungarian', # [cite: 6]
    'hye': 'Armenian', # [cite: 6]
    'ibo': 'Igbo', # [cite: 6]
    'ido': 'Ido', # [cite: 6]
    'ile': 'Interlingue', # [cite: 6]
    'ilo': 'Iloko', # [cite: 6]
    'ina': 'Interlingua', # [cite: 6]
    'ind': 'Indonesian', # [cite: 6]
    'isl': 'Icelandic', # [cite: 6]
    'ita': 'Italian', # [cite: 6]
    'jam': 'Jamaican Patois', # [cite: 7]
    'jav': 'Javanese', # [cite: 7]
    'jbo': 'Lojban', # [cite: 7]
    'jpn': 'Japanese', # [cite: 7]
    'kaa': 'Karakalpak', # [cite: 7]
    'kab': 'Kabyle', # [cite: 7]
    'kan': 'Kannada', # [cite: 7]
    'kat': 'Georgian', # [cite: 7]
    'kaz': 'Kazakh', # [cite: 7]
    'kbd': 'Kabardian', # [cite: 7]
    'khm': 'Central Khmer', # [cite: 7]
    'kin': 'Kinyarwanda', # [cite: 7]
    'kir': 'Kirghiz', # [cite: 7]
    'koi': 'Komi-Permyak', # [cite: 7]
    'kok': 'Konkani', # [cite: 7]
    'kom': 'Komi', # [cite: 7]
    'kor': 'Korean', # [cite: 7]
    'krc': 'Karachay-Balkar', # [cite: 8]
    'ksh': 'Ripuarisch', # [cite: 8]
    'kur': 'Kurdish', # [cite: 8]
    'lad': 'Ladino', # [cite: 8]
    'lao': 'Lao', # [cite: 8]
    'lat': 'Latin', # [cite: 8]
    'lav': 'Latvian', # [cite: 8]
    'lez': 'Lezghian', # [cite: 8]
    'lij': 'Ligurian', # [cite: 8]
    'lim': 'Limburgan', # [cite: 8]
    'lin': 'Lingala', # [cite: 8]
    'lit': 'Lithuanian', # [cite: 8]
    'lmo': 'Lombard', # [cite: 8]
    'lrc': 'Northern Luri', # [cite: 8]
    'ltg': 'Latgalian', # [cite: 8]
    'ltz': 'Luxembourgish', # [cite: 8]
    'lug': 'Luganda', # [cite: 9]
    'lzh': 'Literary Chinese', # [cite: 9]
    'mai': 'Maithili', # [cite: 9]
    'mal': 'Malayalam', # [cite: 9]
    'map-bms': 'Banyumasan', # [cite: 9]
    'mar': 'Marathi', # [cite: 9]
    'mdf': 'Moksha', # [cite: 9]
    'mhr': 'Eastern Mari', # [cite: 9]
    'min': 'Minangkabau', # [cite: 9]
    'mkd': 'Macedonian', # [cite: 9]
    'mlg': 'Malagasy', # [cite: 9]
    'mlt': 'Maltese', # [cite: 9]
    'mon': 'Mongolian', # [cite: 9]
    'mri': 'Maori', # [cite: 9]
    'mrj': 'Western Mari', # [cite: 9]
    'msa': 'Malay', # [cite: 9]
    'mwl': 'Mirandese', # [cite: 9]
    'mya': 'Burmese', # [cite: 10]
    'myv': 'Erzya', # [cite: 10]
    'mzn': 'Mazanderani', # [cite: 10]
    'nan': 'Min Nan Chinese', # [cite: 10]
    'nap': 'Neapolitan', # [cite: 10]
    'nav': 'Navajo', # [cite: 10]
    'nci': 'Classical Nahuatl', # [cite: 10]
    'nds': 'Low German', # [cite: 10]
    'nds-nl': 'West Low German', # [cite: 10]
    'nep': 'Nepali (macrolanguage)', # [cite: 10]
    'new': 'Newari', # [cite: 10]
    'nld': 'Dutch', # [cite: 10]
    'nno': 'Norwegian Nynorsk', # [cite: 11]
    'nob': 'Bokmål', # [cite: 11]
    'nrm': 'Narom', # [cite: 11]
    'nso': 'Northern Sotho', # [cite: 11]
    'oci': 'Occitan', # [cite: 11]
    'olo': 'Livvi-Karelian', # [cite: 11]
    'ori': 'Oriya', # [cite: 11]
    'orm': 'Oromo', # [cite: 11]
    'oss': 'Ossetian', # [cite: 11]
    'pag': 'Pangasinan', # [cite: 11]
    'pam': 'Pampanga', # [cite: 11]
    'pan': 'Panjabi', # [cite: 11]
    'pap': 'Papiamento', # [cite: 11]
    'pcd': 'Picard', # [cite: 11]
    'pdc': 'Pennsylvania German', # [cite: 12]
    'pfl': 'Palatine German', # [cite: 12]
    'pnb': 'Western Panjabi', # [cite: 12]
    'pol': 'Polish', # [cite: 12]
    'por': 'Portuguese', # [cite: 12]
    'pus': 'Pushto', # [cite: 12]
    'que': 'Quechua', # [cite: 12]
    'roa-tara': 'Tarantino dialect', # [cite: 12]
    'roh': 'Romansh', # [cite: 12]
    'ron': 'Romanian', # [cite: 12]
    'rue': 'Rusyn', # [cite: 12]
    'rup': 'Aromanian', # [cite: 12]
    'rus': 'Russian', # [cite: 12]
    'sah': 'Yakut', # [cite: 12]
    'san': 'Sanskrit', # [cite: 13]
    'scn': 'Sicilian', # [cite: 13]
    'sco': 'Scots', # [cite: 13]
    'sgs': 'Samogitian', # [cite: 13]
    'sin': 'Sinhala', # [cite: 13]
    'slk': 'Slovak', # [cite: 13]
    'slv': 'Slovene', # [cite: 13]
    'sme': 'Northern Sami', # [cite: 13]
    'sna': 'Shona', # [cite: 13]
    'snd': 'Sindhi', # [cite: 13]
    'som': 'Somali', # [cite: 13]
    'spa': 'Spanish', # [cite: 13]
    'sqi': 'Albanian', # [cite: 13]
    'srd': 'Sardinian', # [cite: 13]
    'srn': 'Sranan', # [cite: 13]
    'srp': 'Serbian', # [cite: 13]
    'stq': 'Saterfriesisch', # [cite: 13]
    'sun': 'Sundanese', # [cite: 14]
    'swa': 'Swahili (macrolanguage)', # [cite: 14]
    'swe': 'Swedish', # [cite: 14]
    'szl': 'Silesian', # [cite: 14]
    'tam': 'Tamil', # [cite: 14]
    'tat': 'Tatar', # [cite: 14]
    'tcy': 'Tulu', # [cite: 14]
    'tel': 'Telugu', # [cite: 14]
    'tet': 'Tetum', # [cite: 14]
    'tgk': 'Tajik', # [cite: 14]
    'tgl': 'Tagalog', # [cite: 14]
    'tha': 'Thai', # [cite: 14]
    'ton': 'Tongan', # [cite: 14]
    'tsn': 'Tswana', # [cite: 14]
    'tuk': 'Turkmen', # [cite: 14]
    'tur': 'Turkish', # [cite: 14]
    'tyv': 'Tuvan', # [cite: 14]
    'udm': 'Udmurt', # [cite: 14]
    'uig': 'Uighur', # [cite: 14]
    'ukr': 'Ukrainian', # [cite: 15]
    'urd': 'Urdu', # [cite: 15]
    'uzb': 'Uzbek', # [cite: 15]
    'vec': 'Venetian', # [cite: 15]
    'vep': 'Veps', # [cite: 15]
    'vie': 'Vietnamese', # [cite: 15]
    'vls': 'Vlaams', # [cite: 15]
    'vol': 'Volapük', # [cite: 15]
    'vro': 'Võro', # [cite: 15]
    'war': 'Waray', # [cite: 15]
    'wln': 'Walloon', # [cite: 15]
    'wol': 'Wolof', # [cite: 15]
    'wuu': 'Wu Chinese', # [cite: 15]
    'xho': 'Xhosa', # [cite: 15]
    'xmf': 'Mingrelian', # [cite: 15]
    'yid': 'Yiddish', # [cite: 15]
    'yor': 'Yoruba', # [cite: 15]
    'zea': 'Zeeuws', # [cite: 15]
    'zh-yue': 'Cantonese', # [cite: 15]
    'zho': 'Standard Chinese', # [cite: 16]
}