# k8s-hpa-backend.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  # ARCHITECTURAL LIMIT: Capped at 5 to enforce the 2:1 optimal ratio
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35
  # STABILITY NET: Scales up if RAM usage spikes, preventing crashes
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90


        