apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  # ARCHITECTURAL LIMIT: Capped at 5 to enforce the 2:1 optimal ratio
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # STABILITY NET: Scales up if RAM usage spikes (90%), preventing crashes
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  # STABILIZATION: Prevents "Ghost Scaling" during startup
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30 # Aligned with Readiness Probe delay
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300 # Standard 5-min cooldown

